name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.8.1
  widgetbook_annotation: ^3.1.0
  coffee_maker_navigator_2:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  widgetbook_generator: ^3.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
